name: Morning Wake

on:
  push:
    branches:
      - master
  schedule:
    # Runs every 10 mins strictly between 7:30 AM and 8:20 AM IST
    # - cron: '*/10 2 * * *'
    - cron: '*/5 * * * *'
  workflow_dispatch: 

jobs:
  morning_wake_call:
    name: Morning Wake
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Server
        run: |
          curl -I \
          --max-time 120 \
          --retry 3 \
          --retry-delay 10 \
          --retry-connrefused \
          -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36" \
          https://memoria-kz86.onrender.com/api/health